#######################################
# PHP CI - thomasvanzadelhoff.nl
# @author Thomas van Zadelhoff
#######################################
name: Building Docker images

on:
  workflow_call:
    inputs:
      application_type:
        required: true
        type: string
      with_nginx:
        required: true
        default: false
        type: boolean
    secrets:
      token:
        required: true

env:
  registry: ghcr.io

jobs:
  build-and-push:
    name: 🚀 Build & push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🚚 Fetching code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.token }}
          submodules: "recursive"

      - name: 🔑 Authorizing with container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: 🔥 Firing up Docker builder
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: ♻️ Setting up cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.repository }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}

      ###########################
      # Build PHP
      ###########################
      - name: ⤵️ PHP - Adding metadata
        id: php_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ github.repository }}/php
          tags: type=sha,prefix=,format=long

      - name: 🚀 PHP - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .ci/${{ inputs.application_type }}/Dockerfile
          push: true
          target: ${{ inputs.application_type }}
          tags: ${{ steps.php_meta.outputs.tags }}
          labels: ${{ steps.php_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      ###########################
      # Build NGINX
      ###########################
      - name: ⤵️ NGINX - Adding metadata
        if: ${{ inputs.with_nginx }}
        id: nginx_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ github.repository }}/nginx
          tags: type=sha,prefix=,format=long

      - name: 🚀 NGINX - Build and push
        if: ${{ inputs.with_nginx }}
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .ci/${{ inputs.application_type }}/Dockerfile
          push: true
          target: "nginx"
          tags: ${{ steps.nginx_meta.outputs.tags }}
          labels: ${{ steps.nginx_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: ♻️ Saving cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
